### ISSUE TITLE
firstName option not usable

### ISSUE THREAD

**Issue by tillilab** [BobRay/personalize#6]
Hi! Since _$profile_ is taken only if _( !empty ($fullName) )_ on row#114  and since if you set _$fullname_ you never satisfy condition for firstname (row #146), _$firstName_ option does not seem not be usable..

May you could add that exception on row #114?

`if (( !empty ($fullName) )||( !empty ($firstName) )) {`

**Comment by BobRay** [comment]
See if the latest commit on the dev branch fixes it. Let me know.

**Comment by tillilab** [comment]
yes perfect! :)
